config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :my_portfolios, except: [:show]
  get 'my_portfolio/:id', to: 'my_portfolios#show', as: 'my_portfolio_show'
  get 'my_portfolio/:id/edit', to: 'my_portfolios#show', as: 'my_portfolio_edit'
  delete 'my_portfolio/:id', to: 'my_portfolios#destroy', as: 'my_portfolio_delete'
  

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end
end

app/models/my_portfolio.rb
class MyPortfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, reject_if: ->(attributes){ attributes['name'].blank? }
  
  includes Portfolio
  validates_presence_of :title, :body, :main_image, :thumb_image

  scope :with_subtitle, ->(name) { where(subtitle: name) }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/models/portffolio.rb
class Portffolio < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
  includes Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height: '250', width: '250')
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :my_portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
    validates_presence_of :title

    has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception 
    include DeviseWhitelist
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy toggle_status]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show; end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url notice: 'Blog status was successfully changed.'
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
    extend ActiveSupport::Concern
  
    included do
      before_action :configure_permitted_parameters, if: :devise_controller?
    end
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
  end

app/controllers/my_portfolios_controller.rb
class MyPortfoliosController < ApplicationController
  def index
    @my_portfolios = MyPortfolio.all
  end

  def new
    @my_portfolio = MyPortfolio.new
    3.times { @my_portfolio.technologies.build }
  end

  def filter
    filter = params[:items]
    @my_portfolios = MyPortfolio.with_subtitle(items)
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @my_portfolio = MyPortfolio.find(params[:id])
  end

  # GET /my_portfolio/1/edit
  def edit
    @my_portfolio = MyPortfolio.find(params[:id])
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @my_portfolio = MyPortfolio.find(params[:id])
    @my_portfolio.destroy
    respond_to do |format|
      format.html { redirect_to my_portfolios_path, notice: 'Portfolio was successfully removed.' }
    end
  end

  # POST /my_portfolio
  def create
    @my_portfolio = MyPortfolio.new(params.require(:my_portfolio).permit(:title, :subtitle, :body, 
      technologies_attributes: [:name]))

    respond_to do |format|
      if @my_portfolio.save
        format.html { redirect_to my_portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_portfolios/1
  def update
    @my_portfolio = MyPortfolio.find(params[:id])
    respond_to do |format|
      if @my_portfolio.update(params.require(:my_portfolio).permit(:title, :subtitle, :body))
        format.html { redirect_to my_portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts=Blog.all
    @skills=Skill.all
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/my_portfolios_helper.rb
module MyPortfoliosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td> <%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
<di></di>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag 'application',  'data-turbolinks-track': 'reload' %>
  </head>
      
  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <% if current_user %>
       <%= link_to "logout", destroy_user_session_path, method: :delete %>
       <% else %>
       <%= link_to "login", new_user_session_path %>
       <%= link_to "register", new_user_registration_path %>
       <% end %>
       
    <%= yield %>
  </body>
</html>

app/views/my_portfolios/edit.html.erb
<h1>Edit Portfolio Item</h1>

<%= form_for(@my_portfolio) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/my_portfolios/index.html.erb
<h1>Homepage</h1>
<%= link_to "Create New", new_my_portfolio_path %>
<% @my_portfolios.each do |item|%>
    <h4><%= link_to item.title, my_portfolio_show_path(item.id) %></h4>
    <h6><%= item.subtitle %></h6>
    <p><%= item.body %></p>
     <%= image_tag item.thumb_image unless item.thumb_image.nil? %>
     <%= link_to "Edit", my_portfolio_edit_path(item.id) %>
     <%= link_to 'Delete',my_portfolio_delete_path(item.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    <hr>
<% end %>

app/views/my_portfolios/new.html.erb
<h1>Create new Portfolio Item</h1>

<%= form_for(@my_portfolio) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
<ul>
<%= form.fields_for :technologies do |tech_form| %>
<li>
<%= tech_form.label :name %>
<%= tech_form.text_field :name %>
</li>
<% end %>
</ul>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/my_portfolios/show.html.erb
<%= image_tag @my_portfolio.main_image %>

<h1><%= @my_portfolio.title %></h1>

<em><%= @my_portfolio.subtitle %></em>

<p><%= @my_portfolio.body %></p>

<h2>Technologies used:</h2>
<% @my_portfolio.technologies.each do |item|%>

<p><%= item.name %></p>
<% end %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1> Hi, <%= current_user.first_name if current_user %>!</h1>
<%= @posts.inspect %>

<%= @skills.inspect %>